name: Frontend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  frontend:
    name: Frontend - Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js (v20)
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Verify pnpm installation
        run: pnpm --version
        
      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm format:check

      - name: Run tests
        run: pnpm test

      - name: Build Next.js app
        run: pnpm build
