name: CI - Next.js

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  pre-vercel-checks:
    name: Pre-Vercel Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 9.12.3
          node-version: 20

      - name: Vérifier les chemins et l'emplacement de pnpm
        run: |
          echo $PATH
          which pnpm

      - name: Installer pnpm via npm avec nettoyage du cache
        run: |
          npm install -g pnpm@9.12.3
          pnpm --version

      - name: Install dependencies
        run: pnpm install

      - name: Verify commit messages
        run: npx commitlint --from=HEAD~1 --to=HEAD

      - name: Run unit tests
        run: pnpm test

      - name: Lint code
        run: pnpm lint

      - name: Check code formatting
        run: pnpm format:check

      - name: Build application
        run: pnpm build
